### ISSUE TITLE
Create a deep learning model for geolocation prediction

### ISSUE THREAD

**Issue by PolinaPanicheva** [inca-digital/challenge#67]
the task is to create and train an effective DL model that predicts the geographical location of users of a specific Social Media.
### Input data:
1. **timelines**: short texts, varying in languages (think of the ~70 widely used languages of the online world) and numbers (from 0 to thousands for some users);
2. the location the user has identified in their **profile** (sometimes absent, erroneous or non-existent);
3. the profile locations of the users **followed** by the users in our task.

### Prediction target:
location of the users in coordinates: latitude, longitude.

### Training data available:
1. thousands of users with the input data and the ground truth information;
2. millions of individual short texts in the Social Media annotated with geolocation.

### Bonus: 
- deploy the model on Amazon AWS.

### Quick start

- request and download the [**toy development data sample**](https://drive.google.com/drive/u/0/folders/1O1cDspPATNfd1l73Ee5VHKTD9sVehS4P), containing the following (please see description above and in the ReadMe.txt):
   - individual short texts with coordinates (11M);
   - user-level data (97 users):
      - **ground truth** coordinates;
      - **timelines**;
      - **profile** location;
      - **followed** users' location.
- message us at challenge@inca.digital or comment on the issue below with an overview of the suggested model architecture. 
- we will contact the successful applicant for a 40-minute interview and come up with a contract for the model development, provide the rest of the data and GPUs for model training.

Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge@inca.digital.

**Comment by alinapark** [comment]
@romandkane successfully solved the challenge and was hired by Inca Digital.
