### ISSUE TITLE
Online banking providers

### ISSUE THREAD

**Issue by evgenydmitriev** [inca-digital/challenge#73]
Setting aside what's being said on their websites, which European online banking providers would ultimately issue debit cards and provide an IBAN to anyone who has an EU mailing address, regardless of their residency status? Please email careers@inca.digital with one or more examples, and don't forget to attach your resume.

**Comment by bwogisean** [comment]
Attached below is a brief guide to issuances of International Bank Account Numbers by European Bank Provider
[A Guide to IBAN issuances in Europe.pdf](https://github.com/inca-digital/challenge/files/8302824/A.Guide.to.IBAN.issuances.in.Europe.pdf)
s

**Comment by rosi10** [comment]
What about this info
https://www.ecb.europa.eu/pub/pubbydate/2019/html/ecb.cardpaymentsineu_currentlandscapeandfutureprospects201904~30d4de2fc4.en.html
