### ISSUE TITLE
Write marketing brief

### ISSUE THREAD

**Issue by asyaisakova** [inca-digital/challenge#76]
[Inca Digital](https://inca.digital/) would like to build a marketing strategy with the focus on social media promotion.
Purpose: increase employer brand awareness.
Target audience: M/F, 18-24 y.o., data science students and entry level professionals. Interests: remote work, cryptocurrency.
Goal: increase the number of applicants to Investigation Analyst position with technical background by 30% in 3-months period.

Put together 5 briefing questions for Inca Digital, and write reasoning why do you ask each of them.

Please email [careers@inca.digital](mailto:careers@inca.digital) with your ideas, and don't forget to attach your resume.

**Comment by KlayfonKrua** [comment]
Done

**Comment by naranzul** [comment]
Sent.

**Comment by yulia-sergeeva** [comment]
Sent
